@{
    PSDependOptions                                   = @{
        AddToPath  = $true
        Target     = 'output\RequiredModules'
        Parameters = @{
            Repository      = 'PSGallery'
            AllowPreRelease = $true
        }
    }

    InvokeBuild                                       = 'latest'
    PSScriptAnalyzer                                  = 'latest'
    Pester                                            = 'latest'
    Plaster                                           = 'latest'
    ModuleBuilder                                     = 'latest'
    ChangelogManagement                               = 'latest'
    Sampler                                           = 'latest'
    'Sampler.GitHubTasks'                             = 'latest'
    Datum                                             = 'latest'
    'Datum.ProtectedData'                             = 'latest'
    DscBuildHelpers                                   = 'latest'
    'DscResource.Test'                                = 'latest'
    MarkdownLinkCheck                                 = 'latest'
    'DscResource.AnalyzerRules'                       = 'latest'
    'DscResource.DocGenerator'                        = 'latest'

    #DSC Resources
    'Microsoft365DSC'                                 = '1.23.412.1'

    # Required for Microsoft365DSC. This section is generated by running the following command:
    # Update-M365DSCDependencies -ValidateOnly | ForEach-Object { [pscustomobject]$_ }  | ForEach-Object { "'{0}' = '{1}'" -f $_.ModuleName, $_.RequiredVersion } | Set-Clipboard
    'DSCParser'                                       = '1.3.0.6'
    'ExchangeOnlineManagement'                        = '3.1.0'
    'Microsoft.Graph.DeviceManagement'                = '1.25.0'
    'Microsoft.Graph.DeviceManagement.Administration' = '1.25.0'
    'Microsoft.Graph.DeviceManagement.Enrolment'      = '1.25.0'
    'Microsoft.Graph.Devices.CorporateManagement'     = '1.25.0'
    'Microsoft.Graph.Groups'                          = '1.25.0'
    'Microsoft.Graph.Identity.DirectoryManagement'    = '1.25.0'
    'Microsoft.Graph.Identity.Governance'             = '1.25.0'
    'Microsoft.Graph.Identity.SignIns'                = '1.25.0'
    'Microsoft.Graph.Planner'                         = '1.25.0'
    'Microsoft.Graph.Teams'                           = '1.25.0'
    'Microsoft.Graph.Users.Actions'                   = '1.25.0'
    'Microsoft.PowerApps.Administration.PowerShell'   = '2.0.159'
    'MicrosoftTeams'                                  = '5.1.0'
    'MSCloudLoginAssistant'                           = '1.0.105'
    'PnP.PowerShell'                                  = '1.12.0'
    'ReverseDSC'                                      = '2.0.0.14'

}
